spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: (username)
      password: (password)
      database: OnlineJudge
      authentication-database: admin

springdoc:
  paths-to-match:
    - "/api/**"

app:
  security:
    jwt-secret-key: (jwt-secret)
    token-expirations-day: 30
